### ISSUE TITLE
game window running on HMD

### ISSUE THREAD

**Issue by jelle284** [r57zone/OpenVR-OpenTrack#9]
now i don't know if the issue is specific to this driver, but i am having a problem with most steam games where the game window itself (the one thats supposed to run on your computer) starts up on my HMD instead.
I am using a HDMI screen in my headset, and my PC monitor is connected with DVI. I have my pc monitor set as primary, and i configured the driver to display on the secondary screen with the VRsettings tool.
I tried to move the window with windows key + shift + left arrow but it jumps back again immediately

**Comment by r57zone** [comment]
Hello, the problem is not in the driver. You need to install your PC monitor as the primary monitor. The second HDMI VR display needs to be set as advanced. After that, you need to run ["SteamVR Settings"](https://github.com/r57zone/OpenVR-OpenTrack/releases/download/0.6/SteamVR.Settings.zip) (auto install and configure).
If you need to turn on or off the second HDMI display, then there is a program and batch files for this.

**Comment by jelle284** [comment]
I did have my HMD set up as extended display, and PC monitor as primary. I solved it by having the HMD on the left side rather than on the right.
Thanks for quick answer anyway.
